export const Users = [
    {
      id:1,
      profilePicture: "person/nabila.jpg",
      username: "Fatima Nur Nabila",
    },
    {
      id:2,
      profilePicture: "person/ivy.jpg",
      username: "Ivy Bashar",
    },
    {
      id:3,
      profilePicture: "person/jemy.jpg",
      username: "Mahbuba Jemy",
    },
    {
      id:4,
      profilePicture: "person/afsara.jpg",
      username: "Signorina Afsara",
    },
    {
      id:5,
      profilePicture: "person/piyal.jpg",
      username: "Asif Piyal"
    },
    {
      id:6,
      profilePicture: "person/gaffar.jpg",
      username: "Azizul Gaffar",
    },
    {
      id:7,
      profilePicture: "person/sabbir.jpg",
      username: "Sabbir Ahmed",
    },
    {
      id:8,
      profilePicture: "person/lamia.jpg",
      username: "Lamia Farzana",
    },
    {
      id:9,
      profilePicture: "person/salman.jpg",
      username: "Salman Kaisar",
    },
    {
      id:10,
      profilePicture: "person/shanto.jpg",
      username: "Istiak Shanto",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      desc: "Chuckle! I'm in danger",
      photo: "post/danger.jpg",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      desc: "Bibahito Mawlana",
      photo: "post/bibahito.jpg",
      date: "15 mins ago",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      desc: "Sundori",
      photo: "post/sundori.jpg",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      desc: "Dhan Khet",
      photo: "post/afsara_cover.jpg",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      desc: "Boshe Achi",
      photo: "post/boshe.jpg",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      desc: "Gaja khye hobo Raja",
      photo: "post/gaja.jpg",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "Chick Magnet",
      photo: "post/chick.jpg",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      desc: "Imma cool kid, and i know it",
      photo: "post/cool.jpg",
      date: "3 days ago",
      userId: 8,
      like: 15,
      comment: 1,
    },
    {
      id: 9,
      desc: "Shiray Shiray Rokto",
      photo: "post/salman_cover.jpg",
      date: "5 days ago",
      userId: 9,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      desc: "Ame akta pem korta sai",
      photo: "post/shanto_cover.jpg",
      date: "1 week ago",
      userId: 10,
      like: 104,
      comment: 12,
    },
  ];